# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
    identifier = "x"
    name       = "X"
    url        = "https://x.com/miro1152008"

    [social.params]
        icon = "brand-x"

[[social]]
    identifier = "pixiv"
    name       = "Pixiv"
    url        = "https://www.pixiv.net/users/125974832"

    [social.params]
        icon = "pixiv"
