# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
    identifier = "x"
    name       = "X"
    url        = "https://x.com/miro1152008"

    [social.params]
        icon = "twitter"

[[social]]
    identifier = "pixiv"
    name       = "Pixiv"
    url        = "https://www.pixiv.net/users/125974832"

    [social.params]
        icon = "pixiv"

[[social]]
    identifier = "patreon"
    name       = "Patreon"
    url        = "https://www.patreon.com/cw/miro920"

    [social.params]
        icon = "patreon"

[[social]]
    identifier = "unifans"
    name       = "Unifans"
    url        = "https://app.unifans.io/c/miro01"

    [social.params]
        icon = "unifans"
