$ErrorActionPreference = "Stop"

$repoRoot = Resolve-Path (Join-Path $PSScriptRoot "..")
$statsPath = Join-Path $repoRoot "data/site_stats.toml"
$imageRoot = Join-Path $repoRoot "static/post/img"
$contentRoot = Join-Path $repoRoot "content"
$defaultOffset = [TimeSpan]::FromHours(8)

function ConvertTo-SiteDateTimeOffset {
    param([string]$Value)

    $cleanValue = $Value.Trim().Trim('"').Trim("'")
    $parsedOffset = [DateTimeOffset]::MinValue
    if ([DateTimeOffset]::TryParse($cleanValue, [Globalization.CultureInfo]::InvariantCulture, [Globalization.DateTimeStyles]::None, [ref]$parsedOffset)) {
        if ($cleanValue -notmatch '(Z|[+-]\d{2}:?\d{2})$') {
            return [DateTimeOffset]::new($parsedOffset.DateTime, $defaultOffset)
        }

        return $parsedOffset
    }

    return $null
}

function Get-FirstPostDate {
    if (-not (Test-Path $contentRoot)) {
        return $null
    }

    $postFiles = Get-ChildItem -LiteralPath $contentRoot -Recurse -Filter "index.md" |
        Where-Object { $_.FullName -match [regex]::Escape([IO.Path]::DirectorySeparatorChar + "post" + [IO.Path]::DirectorySeparatorChar) }

    $dates = foreach ($file in $postFiles) {
        $dateLine = Get-Content -LiteralPath $file.FullName |
            Where-Object { $_ -match '^\s*date\s*[:=]\s*(.+?)\s*$' } |
            Select-Object -First 1

        if ($dateLine -and $dateLine -match '^\s*date\s*[:=]\s*(.+?)\s*$') {
            ConvertTo-SiteDateTimeOffset $Matches[1]
        }
    }

    $dates | Where-Object { $null -ne $_ } | Sort-Object UtcDateTime | Select-Object -First 1
}

if (Test-Path $statsPath) {
    $existing = Get-Content -Raw -LiteralPath $statsPath
    if ($existing -match '(?m)^last_updated_at\s*=\s*"([^"]+)"') {
        $existingLastUpdatedAt = $Matches[1]
    }
    if ($existing -match '(?m)^update_count\s*=\s*(\d+)') {
        $existingUpdateCount = [int]$Matches[1]
    }
}

$firstPostDate = Get-FirstPostDate
if ($firstPostDate) {
    $siteStartedAt = $firstPostDate.ToString("yyyy-MM-ddTHH:mm:sszzz")
}
else {
    $firstCommitDate = (& git -C $repoRoot log --reverse --format=%cI -n 1 2>$null)
    if ($LASTEXITCODE -eq 0 -and $firstCommitDate) {
        $siteStartedAt = $firstCommitDate.Trim()
    }
    else {
        $siteStartedAt = (Get-Date).ToString("yyyy-MM-ddTHH:mm:ssK")
    }
}

$updateCount = 0
if (Test-Path $imageRoot) {
    $updateCount = @(Get-ChildItem -LiteralPath $imageRoot -Directory).Count
}

if ($null -ne $existingUpdateCount -and $existingUpdateCount -eq $updateCount -and $existingLastUpdatedAt) {
    $lastUpdatedAt = $existingLastUpdatedAt
}
else {
    $lastUpdatedAt = (Get-Date).ToString("yyyy-MM-ddTHH:mm:ssK")
}
$content = @"
# Generated by scripts/update-site-stats.ps1
site_started_at = "$siteStartedAt"
last_updated_at = "$lastUpdatedAt"
update_count = $updateCount
image_collection_count = $updateCount
"@

$content = $content.TrimEnd() + [Environment]::NewLine

if (-not (Test-Path (Split-Path $statsPath))) {
    New-Item -ItemType Directory -Path (Split-Path $statsPath) | Out-Null
}

if ((Test-Path $statsPath) -and ((Get-Content -Raw -LiteralPath $statsPath) -eq $content)) {
    exit 0
}

$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($statsPath, $content, $utf8NoBom)
